Options UI, soundEffects and music buttons and UI and volume change
With one issue as (Assets\Scripts\UI\OptionsUI.cs(22,29): error CS1061: 'Button.ButtonClickedEvent' does not contain a definition for 'AddListner' and no accessible extension method 'AddListner' accepting a first argument of type 'Button.ButtonClickedEvent' could be found (are you missing a using directive or an assembly reference?))